Models/CTMSContext.cs
using Microsoft.EntityFrameworkCore;

namespace ctms_2001.Models;
public class CTMSContext : DbContext
{
    public CTMSContext(DbContextOptions<CTMSContext> options) :
    base(options)
    {

    }

    public DbSet<Tournament> Tournaments { get; set; }
    public DbSet<Player> Players { get; set; }

}

Models/ErrorViewModel.cs
namespace ctms_2001.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Player.cs
namespace ctms_2001.Models;
public class Player
{
    public int Id { get; set; }
    public string? FirstName { get; set; }
    public string? MiddleName { get; set; }
    public string? LastName { get; set; }
    public char Gender { get; set; }
}

Models/Tournament.cs
namespace ctms_2001.Models;
public class Tournament
{
    public int Id { get; set; }
    public string? Name { get; set; }
    public DateOnly StartDate { get; set; }
    public DateOnly EndDate { get; set; }
    public string? Venue { get; set; }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ctms_2001.Models;

namespace ctms_2001.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PlayerController.cs
using ctms_2001.Models;
using Microsoft.AspNetCore.Mvc;

namespace ctms_2001.Controllers;

public class PlayerController : Controller
{
    private readonly CTMSContext _context;

    public PlayerController(CTMSContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        var player = _context.Players.ToList<Player>();
        return View(player);
    }
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Create(Player player)
    {
        _context.Players.Add(new Player
        {
            FirstName = player.FirstName,
            MiddleName = player.MiddleName,
            LastName = player.LastName,
            Gender = player.Gender
        }
        );
        _context.SaveChanges();
        var players = _context.Players.ToList<Player>();
        return View("Index",players);
    }
}

Controllers/TournamentController.cs
using Microsoft.AspNetCore.Mvc;
using ctms_2001.Models;

namespace ctms_2001.Controllers;

public class TournamentController : Controller
{
    private readonly CTMSContext _context;
    public TournamentController(CTMSContext context)
    {
        _context = context;
    }
    public IActionResult Index()
    {
        var tournaments = _context.Tournaments.ToList<Tournament>();
        return View(tournaments);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Tournament tournament)
    {
        _context.Tournaments.Add(new Tournament
        {
            Name = tournament.Name,
            StartDate = tournament.StartDate,
            EndDate = tournament.EndDate,
            Venue = tournament.Venue
        });
        _context.SaveChanges();

        var tournaments = _context.Tournaments.ToList<Tournament>();
        return View("Index", tournaments);
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

Views/Player/Create.cshtml
<form action="" method="post">
    <label for="first_name" class="form-label mt-3">First Name</label>
    <input type="text" name="FirstName" id="first_name" class="form-control">
    <label for="middle_name" class="form-label mt-3">Middle Name</label>
    <input type="text" name="MiddleName" id="middle_name" class="form-control">
    <label for="last_name" class="form-label mt-3">Last Name</label>
    <input type="text" name="LastName" id="last_name" class="form-control">
    <label for="gender" class="form-label mt-3">Gender</label>
    <input type="text" name="gender" id="gender" class="form-control">
    <button class="mt-3 btn btn-primary">Submit</button>


</form>

Views/Player/Index.cshtml
@model List<Player>
<div>
    <div class="row">
        <div class="col-sm">
            <h1>Players</h1>
        </div>
        <div class="col-sm" style="text-align: right;">
            <a class="btn btn-primary mt-3" asp-controller="Player" asp-action="Create">New Player</a>
        </div>
    </div>
    <table class="table mt-5">
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th colspan="3"></th>
        </tr>
        @foreach(var player in Model)
        {
            <tr>
                <td>@player.Id</td>
                <td>@player.FirstName</td>
                <td>@player.MiddleName</td>
                <td>@player.LastName</td>
                <td>@player.Gender</td>
                <td><a href="">Edit</a></td>
                <td><a href="">Delete</a></td>
            </tr>
        }
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ctms_2001</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ctms_2001.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CTMS-2001</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tournament" asp-action="Index">Tournament</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Player</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CTMS-2001
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tournament/Create.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Tournament</title>
</head>
<body>
    <h1>Create Tournament</h1>
    <form action="" method="post">
        <label for="name" class="form-label mt-3">Name</label>
        <input type="text" name="name" id="name" class="form-control">
        <label for="startdate" class="form-label mt-3">Start Date</label>
        <input type="date" name="startdate" id="startdate" class="form-control">
        <label for="end_date" class="form-label mt-3">End Date</label>
        <input type="date" name="enddate" id="enddate" class="form-control">
        <label for="venue" class="form-label mt-3">Venue</label>
        <input type="text" name="venue" id="venue" class="form-control">
        <button class="btn btn-primary mt-3">Submit</button>
    </form>
</body>
</html>

Views/Tournament/Index.cshtml
@model List<Tournament>
<div>
    <div class="row">
        <div class="col-sm">
            <h1>Tournaments</h1>
        </div>
        <div class="col-sm" style="text-align: right;">
            <a class="btn btn-primary mt-3" asp-controller="Tournament" asp-action="Create">New Tournament</a>
        </div>
    </div>
    <table class="table mt-5">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Venue</th>
            <th colspan="3"></th>
        </tr>
        @foreach (var tournament in Model)
        {
            <tr>
                <td>@tournament.Id</td>
                <td>@tournament.Name</td>
                <td>@tournament.StartDate</td>
                <td>@tournament.EndDate</td>
                <td>@tournament.Venue</td>
                <td><a href="">Display</a></td>
                <td><a href="">Edit</a></td>
                <td><a href="">Delete</a></td>
            </tr>
        }
    </table>
</div>